baseURL: https://johnnymetz.com/
title: Johnny Metz
theme: PaperMod
paginate: 5
disqusShortname: johnnymetz

# env vars set on server so we're not committing a secret to version control
# - HUGO_GOOGLEANALYTICS

params:
  title: Johnny Metz
  author: Johnny Metz
  description: Johnny Metz's personal website and blog
  keywords: [blog, developer, portfolio]
  DateFormat: 'January 2, 2006'
  defaultTheme: auto

  ###################
  # Site-wide
  ###################

  hideFooter: true

  label:
    text: Johnny Metz
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  assets:
    disableHLJS: true # use Hugo's syntax highlighter "Chroma" instead of highlight.js
    # disableFingerprinting: true
    # favicon: '<link / abs url>'
    # favicon16x16: '<link / abs url>'
    # favicon32x32: '<link / abs url>'
    # apple_touch_icon: '<link / abs url>'
    # safari_pinned_tab: '<link / abs url>'

  # analytics:
  #   google:
  #     SiteVerificationTag: 'XYZabc'

  # cover:
  #   hidden: false # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  ###################
  # Home
  ###################

  homeInfoParams:
    # Title: "Hi there \U0001F44B"
    Title: Welcome to my blog
    # Content: Welcome to my blog

  socialIcons:
    - name: YouTube
      url: 'https://www.youtube.com/channel/UCvsoVkN5D3YUqfqRUz_HLcg'
    - name: LinkedIn
      url: 'https://www.linkedin.com/in/jonathancmetz/'
    - name: Github
      url: 'https://github.com/johnnymetz'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/6611672/johnny-metz'
    - name: email
      url: 'mailto:contact@johnnymetz.com'

  # disableSpecial1stPost: false # not applicable in home-info mode
  # hideSummary: true

  ###################
  # SINGLE POST
  ###################

  ShowBreadCrumbs: true
  # hidemeta: true # post header: date, time, author
  ShowReadingTime: true
  # ShowToc: true
  # TocOpen: true

  # Suggest changes
  # editPost:
  #   URL: 'https://github.com/<path_to_repo>/content'
  #   Text: 'Suggest Changes' # edit text
  #   appendFilePath: true # to append file path to Edit link

  ShowCodeCopyButtons: true
  # disableScrollToTop: true

  ShowShareButtons: true
  ShowPostNavLinks: true

  comments: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

# for search
outputs:
  home:
    - HTML
    - RSS # /index.xml
    - JSON # /index.json

menu:
  main:
    - name: Blog
      url: blog/
      weight: 10
    - name: About
      url: about/
      weight: 20
    - name: Subscribe
      url: subscribe/
      weight: 30
    - name: Tags
      url: tags/
      weight: 40
    - name: Search
      url: search/
      weight: 50

# https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
  highlight:
    # lineNos: true

minify:
  disableXML: true
  minifyOutput: true

enableEmoji: true
enableRobotsTXT: true
