baseURL: 'http://www.example.com'
title: Johnny Metz
theme: hugo-coder
paginate: 10
enableEmoji: true
params:
  version: 2.0.X
  app:
    title: Johnny Metz
    noFavicon: true
  home:
    rss: 10
    profile:
      enable: true
      avatarURL: https://ui-avatars.com/api/?name=J+M&background=0D8ABC&color=fff
      title: Johnny Metz
      subtitle: Johnny Metz's personal website and blog
      social: true
    posts:
      enable: true
  social:
    - name: Github
      icon: fa fa-github
      weight: 1
      url: 'https://github.com/johnnymetz'
    - name: LinkedIn
      icon: fa fa-linkedin
      weight: 4
      url: 'https://www.linkedin.com/in/jonathancmetz/'
    - name: LinkedIn
      icon: fa fa-youtube
      weight: 4
      url: 'https://www.youtube.com/channel/UCvsoVkN5D3YUqfqRUz_HLcg'
menu:
  main:
    - name: Blog
      url: blog/
    - name: Most Popular
      url: most-popular/
    - name: About
      url: about/
    - name: Tags
      url: tags/
taxonomies:
  tag: tags
# permalinks:
#   blog: '/blog/:year/:slug/'
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    # lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
