[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"

[context.dev]
command = "hugo --gc --minify --buildDrafts --buildFuture -b https://dev.johnnymetz.com"

[context.dev.environment]
HUGO_VERSION = "0.88.1"
