# baseURL: 'http://www.example.com'
title: Johnny Metz
theme: hugo-coder
paginate: 10
enableEmoji: true

# pass as HUGO_GOOGLEANALYTICS env var
googleAnalytics:

params:
  author: Johnny Metz
  description: Johnny Metz's personal website and blog
  keywords: 'blog,developer,personal'
  info: Full Stack Software Engineer
  dateFormat: 'January 2, 2006'
  hideFooter: true
  since: 2021
  colorScheme: auto
  social:
    - name: Github
      icon: fa fa-github
      url: 'https://github.com/johnnymetz'
    - name: LinkedIn
      icon: fa fa-linkedin
      url: 'https://www.linkedin.com/in/jonathancmetz/'
    - name: YouTube
      icon: fa fa-youtube
      url: 'https://www.youtube.com/channel/UCvsoVkN5D3YUqfqRUz_HLcg'
    - name: StackOverflow
      icon: fa fa-stack-overflow
      url: 'https://stackoverflow.com/users/6611672/johnny-metz'

menu:
  main:
    - name: Blog
      url: blog/
      weight: 1
    - name: About
      url: about/
      weight: 2
    - name: Tags
      url: tags/
      weight: 3

taxonomies:
  tag: tags

# permalinks:
#   blog: '/blog/:year/:slug/'

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    # lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
